services:
  - type: web
    name: context-snake
    env: node
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "20"
